### ISSUE TITLE
 Package 'gtkmm-3.0' not found!

### ISSUE THREAD

**Issue by JerryGoyal** [cppit/jucipp#173] opened 2016-03-28 08:41 UTC
I'm following the official guide to install and run jucipp on my windows10 x64.
when I execute the command "`cmake -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw64 ..`"
I get the following error:
```
liblldb not found. Building juCi++ without debugging support
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   thread
--   log
--   system
--   filesystem
--   regex
-- Checking for module 'gtkmm-3.0'
--   Package 'gtkmm-3.0' not found
CMake Error at C:/msys64/mingw64/share/cmake-3.4/Modules/FindPkgConfig.cmake:365 (message):
  A required package was not found
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.4/Modules/FindPkgConfig.cmake:527 (_pkg_check_modules_internal)
  src/CMakeLists.txt:49 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/Jerry/jucipp/build/CMakeFiles/CMakeOutput.log".
```

**Comment by eidheim** [comment] 2016-03-28 08:43
Duplicate of #172 . MSYS2 is currently broken if you have upgraded in the last days, but will be fixed in a day or two hopefully.

**Closed by eidheim** 2016-03-28 08:43 UTC

**Comment by JerryGoyal** [comment] 2016-03-28 08:44
I just updated MSYS2. I wasn't aware of this issue. thanks.
