### ISSUE TITLE
CMake support is very invasive and modifies my files

### ISSUE THREAD

**Issue by kvakvs** [cppit/jucipp#132] opened 2015-12-18 13:45 UTC
Tried juci with my project which uses Makefile and CMake under it, in a subdirectory (https://github.com/kvakvs/gluonvm)
What I got:
* it overwrote my Makefile (very bad)
* it used gcc automatically even if CMakeLists said use clang, well actually i create my CMakefile-based Makefile using shell script and then just run make. So don't assume compiler (bad)
* it assumed own directory structure and dropped CMake cache dir and cache files in project directory, even though makefile tries to keep all build files under _build directory (bad, too many assumptions)

Please don't modify or overwrite project files. This gives bad karma.
Please don't assume user build directories or compiler.
Perfectly would love to be able to run make (make -j8) and have my project work without juci trying to guess everything for me.

**Comment by eidheim** [comment] 2015-12-18 13:51
This is also a duplicate of #121 (and #131), see especially at the end, where I'm actually starting to make sense. Will most likely use the boost syntax for path variables though, <> instead of {}. I got to read up on this, but comments are welcome. It will not take more than a few hours to implement, but have to make sure I do not do anything stupid that will affect future versions of juCi++.

**Comment by eidheim** [comment] 2015-12-18 13:54
And actually, you need to use CMAKE_CXX_COMPILER when running cmake to use clang instead of the default compiler. According to https://cmake.org/Wiki/CMake_Useful_Variables you can also do this after the cmake cache files has been made. We will not implement a gui for this, since it is so easy to do in either Run Command or a terminal.

**Comment by eidheim** [comment] 2015-12-18 15:07
Also, after the build directory is implemented, you will be able to use Run Command: make && ./your_executable if you open juCi++ in your emulator path. The build directory will be made, but this is just so that juCi++ will be able to parse your C/C++ files, and your makefile in emulator will not be touched.

**Comment by eidheim** [comment] 2015-12-19 11:38
You can now try out the new build path solution:
```sh
git clone -b build_dir_fixed --recursive http://github.com/cppit/jucipp
```

**Closed** 2015-12-22 08:08 UTC
Labels: duplicate, solved
