### ISSUE TITLE
Use existing build dir / configuration

### ISSUE THREAD

**Issue by pgoodman** [cppit/jucipp#131] opened 2015-12-17 15:33 UTC
I have a project with an existing build directory. I use CMake to generate the makefile in that directory, but the CMake invocation requires some special parameters. Ideally, I would like for jucipp to be able to use that build directory as opposed to rebuilding my code in the root of the source tree.

**Comment by eidheim** [comment] 2015-12-17 16:17
I think this is a duplicate of #121. See especially the last 3 comments. The solution that I'm thinking of in the last post should be very flexible and work for everyone I think, no matter their preferred way of doing things. Also look at the pros and cons, based the solution somewhat on this. Of course, if you disagree, let me know!

If you have a special configuration already in a build dir, juCi++ will continue to use these if they're in the default_build_path (when this finally is implemented). The current version also works like that, cache files are never replaced unless you do that manually, however, of course we have hardcoded the build dir to ".".

**Comment by eidheim** [comment] 2015-12-19 11:38
You can now try out the new build path solution:
```sh
git clone -b build_dir_fixed --recursive http://github.com/cppit/jucipp
```

**Closed** 2015-12-22 08:08 UTC
Labels: duplicate, solved
