### ISSUE TITLE
code parser does not honour cmake_prefix_path?

### ISSUE THREAD

**Issue by plhofoan** [cppit/jucipp#240] opened 2016-06-06 08:05 UTC
I pass the command -DCMAKE_PREFIX_PATH=... to cmake (configured in the config.json) as I have some libraries in a non standard path. In the CMakeLists.txt I also do "include_directories(...)".

Building of the project works as expected, but the parsing of the code shows lots of errors, as the include-files are not found - only include-files in the standard paths are found..

**Comment by eidheim** [comment] 2016-06-06 08:12
CMAKE_PREFIX_PATH should only affect the `Find_*` commands. What OS are you on? Also, take a look at your ./build/compile_commands.json and see if you can find the problem in its paths there.

**Comment by eidheim** [comment] 2016-06-06 08:33
This should solve it I think, either:
* open a CMakeLists.txt, modify it (for instance add a space and remove it), and save
or
* remove the build directory and reopen the files

**Comment by eidheim** [comment] 2016-06-07 11:09
If you were on MSYS2, there were problems with included directories due to a slight change in MSYS2 at some point. It is fixed now though.

**Comment by plhofoan** [comment] 2016-07-04 09:35
sorry for my late replay, I was out of office for a while..
Yes, I am using MSYS2, but the workaround (and most recent version) didn't help.

Looking at the compile_commands.json I noticed that the paths are written in different formats: 
- on one hand there is this part: "-isystem /C/msys/home/foo/bar", which is the include-file that isn't found during parsing.
- then there are a lot of "-IC:/msys/some/default/paths", which are found..

As soon as I change the first one to "-isystem C:/msys/home/foo/bar", the parsing works fine an no more errors are shown. Still, this only affects parsing, not compiling, which works either way.

When I look at the compile_commands of jucipp, there all paths are the "/C/msys/.."-way - and still works.

**Comment by eidheim** [comment] 2016-07-04 10:00
Thank you. The problem is probably here: https://github.com/cppit/jucipp/blob/master/src/cmake.cc#L76. We look for `-Isome_path` and fixes that for Windows and MSYS2, but we do not look for "`-i system some_path`. You might be able to fix this yourself and make a pull request? If not, I'll have a look at it in a couple of days.

**Comment by eidheim** [comment] 2016-07-04 15:43
Fixed in #249

**Closed by eidheim** 2016-07-04 15:43 UTC
