### ISSUE TITLE
yotta integration

### ISSUE THREAD

**Issue by autopulated** [cppit/jucipp#119] opened 2015-12-14 16:22 UTC
What do you think about integrating [yotta](https://github.com/ARMmbed/yotta)?

It's a module system for C & C++, with build-system based around CMake.

**Comment by zalox** [comment] 2015-12-14 16:33
I guess this should be possible to implement as a plugin with our plugin system arriving in one of the next releases.

**Comment by autopulated** [comment] 2015-12-14 16:36
:+1: Sounds cool – just wanted to point it out to you as seems like it might be a really good fit.

**Comment by eidheim** [comment] 2015-12-14 17:54
See also #97

**Comment by eidheim** [comment] 2015-12-15 14:23
Closing this as it is somewhat a duplicate of #97, added your link there instead:)

**Closed by eidheim** 2015-12-15 14:23 UTC
Labels: duplicate

**Comment by autopulated** [comment] 2015-12-15 15:38
:thumbsup:
