### ISSUE TITLE
enhance autocompletion

### ISSUE THREAD

**Issue by Krokoklemmi** [cppit/jucipp#328] opened 2017-03-31 02:56 UTC
autocompletion for include files non-existent and it would be nice if you could bring up the code-completion window via CTRL+Space or something like that.

it could also use some UI/UX enhancements

**Comment by eidheim** [comment] 2017-03-31 17:17
I'm closing this issue since it is somewhat a duplicate of #327. You can add a shortcut for code-completion, see preferences.

**Closed by eidheim** 2017-03-31 17:17 UTC
