### ISSUE TITLE
Arch linux, error on launch

### ISSUE THREAD

**Issue by Bl4ckb0ne** [cppit/jucipp#192] opened 2016-04-12 23:55 UTC
Hi, I just discovered your IDE, and I wanted to try it. 
From both aur and the manual installation, I got the same error :

```sh
: CommandLine Error: Option 'aarch64-reserve-x18' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

I'm running arch on the latest available kernel
```sh
Linux cthulhu 4.5.0-1-ARCH #1 SMP PREEMPT Tue Mar 15 09:41:03 CET 2016 x86_64 GNU/Linux
```

Is this a known bug? I tried to reinstall it without lldb, but I still got the error.

Thanks!

**Comment by eidheim** [comment] 2016-04-13 06:07
Yes this is a known issue. Have a look at the links in #191 (this is a duplicate of this issue). 

The workaround is to build juCi++ without debug support: uninstall lldb, remove jucipp/build, and then follow the build/install instructions from and including `mkdir jucipp/build`.

**Closed by eidheim** 2016-04-13 06:07 UTC
