### ISSUE TITLE
jucicpp as neovim gui client

### ISSUE THREAD

**Issue by 8l** [cppit/jucipp#167] opened 2016-03-15 22:37 UTC
Hi, i want to use jucipp as neovim gui client, like neovim-qt.
https://github.com/equalsraf/neovim-qt

TIA

**Comment by eidheim** [comment] 2016-03-16 11:23
Could you elaborate? Not sure if I understand the issue.

**Comment by 8l** [comment] 2016-03-16 12:31
i want to use vim mode in jucipp, this is practical approach, IMHO.
that's all.

**Comment by eidheim** [comment] 2016-03-16 13:09
Then this is a duplicate of #163. Please see this issue, and the suggestions we have there, especially have a look at this link: http://vim.wikia.com/wiki/Vi_key_bindings_in_gtk.

**Closed by eidheim** 2016-03-16 13:09 UTC

**Comment by eidheim** [comment] 2016-03-16 13:12
And feel free to post your solution if you find a way to do this without altering the juCi++ source code.
